### ISSUE TITLE
Establish means of getting user feedback about app in general

### ISSUE THREAD

**Issue by MufasaTheMusician** [MufasaTheMusician/eatwithme#112]
We need some way to collect feedback from alpha testers - whether that's an email address to send it to or something different

**Comment by ttww97** [comment]
I have set the feedback email which is Info.eatwithmeapp@gmail.com.
After publishing, we can do internal test with other versions of the app.

**Comment by ttww97** [comment]
After testing, all testers who can download the app can post their feedbacks in the page of Google Play. And we can see the result in the User Feedback page.
