### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by MufasaTheMusician** [MufasaTheMusician/eatwithme#118]
We need an icon for the app before we can release anywhere - probably themed around the smiley face I imagine :)

**Comment by BenjaminStorer** [comment]
Mocked up several icon designs. Here's what they might look like on a home screen.
![image](https://user-images.githubusercontent.com/49058688/64123500-e4b94f80-cde7-11e9-96b0-cf470da282ae.png)

**Comment by BenjaminStorer** [comment]
Created a few extra designs and edited a couple. Theres roughly 10 designs now.
