### ISSUE TITLE
Discuss Interests database schema

### ISSUE THREAD

**Issue by BenjaminStorer** [MufasaTheMusician/eatwithme#28]
Implement how interests look in Firebase and their relationships to each other.

**Comment by MufasaTheMusician** [comment]
This blocks a lot of interests tasking, need to identify what fields we need and how it will work in Firebase

**Comment by MufasaTheMusician** [comment]
From our meetings, we've decided on matching by name, some sort of method for implicit matching with the interests of people spoken to and using a tree structure for interests, so Firebase will have an Interests collection (id, name, children) and Users will have a list of interest ids with some sort of scoring or ability to add more interests to the list. Additional fields might be identified as we design interest similarity matching
