### ISSUE TITLE
Build new Interests UI Page

### ISSUE THREAD

**Issue by Joel-Groves** [MufasaTheMusician/eatwithme#35]
Includes:

* building the new Interests page's UI (two lists)
* linking it to be accessed from the Edit Interests button on the Edit Profile page

**Comment by MufasaTheMusician** [comment]
We need to work out how to split this up or assign task to one person

**Comment by MufasaTheMusician** [comment]
There's a widget called ExpandingNoteBar that will be useful in implementing the search bar for interests

**Comment by MufasaTheMusician** [comment]
![](https://i.imgur.com/VRc62K5.jpg)

**Comment by MufasaTheMusician** [comment]
@Joel-Groves, just realised that your code for this part uses all the old interests database writes and breaks, please make sure to use the new stuff next time. I'll fix it up since I need to test my functions and we're running out of time.
