### ISSUE TITLE
Importing initial list of interests into Firebase

### ISSUE THREAD

**Issue by Joel-Groves** [MufasaTheMusician/eatwithme#38]
Need an initial list of interests/hobbies for people to select from

Can be scraped from https://en.wikipedia.org/wiki/List_of_hobbies as a starting point, but others can be added too

**Comment by MufasaTheMusician** [comment]
This needs to be in a hierarchy in Firebase (Interests with children)

**Comment by MufasaTheMusician** [comment]
Given our use cases, we should take extra care to fill main categories Languages, Sport and Games

**Comment by MufasaTheMusician** [comment]
@ROXtiGerf, for the sake of time, just put them in as a flat collection ("Interests") with an id and name - we can change it later if we need.

I recommend taking the wikipedia List of Hobbies into a spreadsheet and finding a way to import CSV into Firebase.

**Comment by MufasaTheMusician** [comment]
Has there been any progress made on this?

**Comment by ROXtiGerf** [comment]
Sorry, I had an assignment to due tomorrow. For now, I just need to fill all interests in to ' Languages, Sport and Games' these three categories right? For example: 
Sport:
1, football
2, running
Languages:
3, English
Games:
4, boardgame

**Comment by MufasaTheMusician** [comment]
If you're going to put them in categories, make as many as you need using sub collections. If the JSON importing for sub collections is too tricky, importing them flat for now is OK and we'll work it out after alpha

**Comment by MufasaTheMusician** [comment]
How is this coming @ROXtiGerf? It's pretty critical to alpha, so if you're having trouble and can't get it I can do it

**Comment by MufasaTheMusician** [comment]
I've done a quick import of the list on Wikipedia just to have some data in there, still needs to be put in sub categories later on post alpha

**Comment by ROXtiGerf** [comment]
Thanks, I didn't know how to import from Wikipedia.
