### ISSUE TITLE
Implement CI/CD dev flow

### ISSUE THREAD

**Issue by MufasaTheMusician** [MufasaTheMusician/eatwithme#61]

**Comment by MufasaTheMusician** [comment]
Hey @ttww97 @Guang980803, on the last build after the iOS merge the Android build failed, some exceptions were caught by the test framework, is this related to the unit tests in #58? As far as I can tell, app is working fine from the latest build so it should have gone through

https://codemagic.io/app/5d53ca7b5ce262000dc52e57/build/5d63f33129657a000fcf7d10

**Comment by Guang980803** [comment]
The build failed for the development branch is probably because the missing jason file from android/app, i had added the jason file to the newDV branch and the build passed.

**Comment by Guang980803** [comment]
I tested on the newDV branch in order not to mess up with the main development branch. After the build passed for the newDV branch, all the related apks are sent to my email automatically.

**Comment by ttww97** [comment]
We tested the workflow this afternoon. It works well.
