### ISSUE TITLE
Fix API keys with Codemagic and repos

### ISSUE THREAD

**Issue by MufasaTheMusician** [MufasaTheMusician/eatwithme#62]
* Need to make sure no API keys are in plaintext and on a repo
* Store keys with Codemagic in a secure manner

**Comment by MufasaTheMusician** [comment]
Could we please have an update on this one guys? Just a comment about how we're storing keys and confirming they are in the gitignore file :)

**Comment by MufasaTheMusician** [comment]
@ttww97 and @Guang980803, please update as above when you get a chance

**Comment by Guang980803** [comment]
Still working on it with TingWei, will figure out soon.
