### ISSUE TITLE
Investigate Flare as a UI development tool

### ISSUE THREAD

**Issue by BenjaminStorer** [MufasaTheMusician/eatwithme#79]
Exploring Flare and the limits of its functionality to see if it’s a viable tool to create UI and animations for the app.

Key concerns
* Productivity of workflow
* Read/write states to the widget
* Read/Write dynamic data to widget

**Comment by BenjaminStorer** [comment]
I've spent a little bit of time working with Flare so I have a bit more of an understanding of how it works and its use cases. 

Flare allows you to animate vector graphics using a traditional animation tool. It's really useful for animating icons and menus to give them more personality than could easily be done in Flutter. Its benefits are to increased workflows.

Once in Flutter, the flare animations can be played and dynamically tweened. The UI of the flare file can be easily placed in a scene. However it doesn't provide any extra functionality as far as I can tell. We can detect certain touch points, gestures using Flutter and use that as data to play the animations but we can't directly modify the properties of any of the UI being animated.

**Comment by MufasaTheMusician** [comment]
Sweet, a lot of potential for different bits of UI. Sounds like this is all good, so I'll close it as done
