### ISSUE TITLE
Fix iOS problems

### ISSUE THREAD

**Issue by ttww97** [MufasaTheMusician/eatwithme#86]
The refactored code can’t be run for iOS.
Trying to fix this bug.

**Comment by ttww97** [comment]
Seems the problem comes from non-swift based project (the similar problem happened last semester).
One way is to create new swift-based flutter project. However, it can’t send pull request in this case. 
Working on it now.

**Comment by MufasaTheMusician** [comment]
@ttww97, would you be able to leave a comment on what you changed just so we have it in the card?

I'll pull it out of your branch and merge to dev

**Comment by MufasaTheMusician** [comment]
Nice work guys :)
